// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    EosIconsLoading: typeof import('~icons/eos-icons/loading')['default']
    MdiContentCopy: typeof import('~icons/mdi/content-copy')['default']
  }
}

export { }
